services:
  backend:
    build: ./fastapi_todo_backend
    container_name: todo_backend
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi_todo_backend/.env
    depends_on:
      - db
    restart: always

  frontend:
    build: ./fastapi_todo_frontend
    container_name: todo_frontend
    ports:
      - "5173:80"
    restart: always

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_user_gr
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
